### PR TITLE
Actually fix the yaw this time

### PR DESCRIPTION
**Pull request by HimbeersaftLP**
Switch to a better way of rounding that rounds to the closest multiple of 45°

### CODE REVIEW

**Comment by benda95280** [comment]
Works like a charm ! Thanks !

**Comment by HimbeersaftLP** [comment]
May I ask why this is not a fork of Enes5519's plugin?

**Comment by benda95280** [comment]
When started, was thinking to start from scratch  ... After that, wasn't thinking about it ...
But you'r right, but don't know how to do now (i'm new on github)

**Comment by benda95280** [comment]
I'm thinking to add new entity too, (that's why i've added new variable in config.yml) maybe like:
- Life dispenser (Skin+Json geometry in a folder) + config (number of recharge, how much life, speed to add new recharge)
- Custom object (see mpcedl, like furnicraft ...)
- Mask support, with effect, particule? ... (Looking to everybodythonk source code)
- ... Many possibilities ...

Just thinking :)

**Pull request merged**
