### PR TITLE
Major rewrite of code

### PR DESCRIPTION
**Pull request by benda95280**

### CODE REVIEW

**Comment by benda95280** [comment]
> this is not healing me

I've just tested with Book_1 (Without this PR), works. 
[EDIT] Tested LifeDispenser too, works

**Comment by inxomnyaa** [comment]
I will try to resolve the conflicts asap, but since my phone constantly crashes recently i am having some trouble with internet access at home

**Comment by inxomnyaa** [comment]
Solved, can be merged

**Comment by benda95280** [comment]
> LifeDispenser.gif is 7.5 MB.

Thanks, will get it out asap

**Comment by benda95280** [comment]
@SOF3 Thanks, i've fixed it.

**Pull request merged**
